#!make -f

CC=gcc
CFLAGS=-Wall -Wextra -fPIC -Wunused-parameter -Wno-unused-parameter
LIBRARIES_NAMES=libcodecA.so libcodecB.so
LIBRARIES_PATH=-L. -Wl,-rpath=. libcodecA.so libcodecB.so


.PHONY: all clean

all: encode decode cmp copy stshell

encode: encode.o $(LIBRARIES_NAMES)
	$(CC) -o encode encode.o $(LIBRARIES_PATH)

decode: decode.o $(LIBRARIES_NAMES)
	$(CC) -o decode decode.o $(LIBRARIES_PATH)

libcodecA.so: codecA.o
	$(CC) -shared -o libcodecA.so codecA.o

libcodecB.so: codecB.o
	$(CC) -shared -o libcodecB.so codecB.o

codecA.o: codecA.c codecA.h
	$(CC) $(CFLAGS) -c codecA.c -o codecA.o 

codecB.o: codecB.c codecB.h
	$(CC) $(CFLAGS) -c codecB.c -o codecB.o 

encode.o: encode.c
	$(CC) $(CFLAGS) -c encode.c

decode.o: decode.c
	$(CC) $(CFLAGS) -c decode.c

cmp: cmp.o
	$(CC) -o cmp cmp.o

cmp.o: cmp.c
	$(CC) $(CFLAGS) -c cmp.c

copy: copy.o
	$(CC) -o copy copy.o

copy.o: copy.c
	$(CC) $(CFLAGS) -c copy.c

stshell: stshell.o
	$(CC) -o stshell stshell.o	

stshell.o: stshell.c
	$(CC) $(CFLAGS) -c stshell.c 	

clean:
	rm -f encode decode cmp copy stshell $(LIBRARIES_NAMES) *.o 

